# Generated by Django 3.0.7 on 2020-06-27 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='sub_category',
            field=models.CharField(default='Vegitables', max_length=100),
            preserve_default=False,
        ),
    ]
