# Generated by Django 3.0.7 on 2020-06-27 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_subcategory_sub_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='sub_category',
            new_name='sub_category_name',
        ),
    ]
