# Generated by Django 3.0.7 on 2020-06-27 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200628_0531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemdetails',
            name='description',
        ),
    ]
