# Generated by Django 3.0.7 on 2020-06-28 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200628_0551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemdetails',
            options={'ordering': ['update_date']},
        ),
        migrations.AlterField(
            model_name='itemdetails',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.Items'),
        ),
    ]
