# Generated by Django 3.0.7 on 2020-06-28 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20200628_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdetails',
            name='total_views',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
