# Generated by Django 3.0.7 on 2020-06-28 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_itemdetails_total_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdetails',
            name='total_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='items',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Images'),
        ),
    ]
