# Generated by Django 3.0.7 on 2020-06-28 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20200629_0427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='image',
        ),
        migrations.CreateModel(
            name='ItemImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/images/')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Items')),
            ],
        ),
    ]
