# Generated by Django 3.0.7 on 2020-07-02 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20200702_1958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='District',
            new_name='district',
        ),
    ]
