# Generated by Django 3.0.7 on 2020-07-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20200705_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_id',
            field=models.CharField(default='Somikoron', max_length=10),
            preserve_default=False,
        ),
    ]
