# Generated by Django 3.0.7 on 2020-07-05 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_category_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='item_owner',
            new_name='itemowner',
        ),
        migrations.AlterField(
            model_name='cattleinfo',
            name='Breed',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cattleinfo',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.Items'),
        ),
        migrations.AlterField(
            model_name='items',
            name='sub_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='subcat', to='shop.SubCategory'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(default='Others', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='maincat', to='shop.Category'),
        ),
    ]
