# Generated by Django 3.0.7 on 2020-07-05 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20200705_2213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='itemowner',
            new_name='item_owner',
        ),
        migrations.AlterField(
            model_name='items',
            name='sub_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='shop.SubCategory'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(default='Others', on_delete=django.db.models.deletion.SET_DEFAULT, to='shop.Category'),
        ),
    ]
