# Generated by Django 3.0.7 on 2020-07-05 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_remove_items_item_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='item_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.OwnerInfo'),
        ),
    ]
