# Generated by Django 3.0.7 on 2020-07-05 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_items_item_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='sub_category',
            new_name='subcategory',
        ),
    ]
