# Generated by Django 3.0.7 on 2020-07-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_auto_20200705_2251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cattleinfo',
            old_name='weight',
            new_name='expected_weight',
        ),
        migrations.AddField(
            model_name='cattleinfo',
            name='live_weight',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
    ]
