# Generated by Django 3.0.7 on 2020-07-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_auto_20200716_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('RECEIVED', 'Order Received'), ('SHIPPING', 'Order is on the way'), ('DONE', 'Order Completed'), ('CANCELED', 'Order Canceled')], default='RECEIVED', max_length=20),
        ),
    ]
