# Generated by Django 3.0.7 on 2020-07-18 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_auto_20200718_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cattleinfo',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cattleinfo', to='shop.Items'),
        ),
        migrations.AlterField(
            model_name='itemdetails',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='itemdetails', to='shop.Items'),
        ),
    ]
