# Generated by Django 3.0.7 on 2020-07-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_auto_20200720_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='customer_phone',
            field=models.CharField(default='0177777777', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('PLACED', 'Order Placed'), ('RECEIVED', 'Order Received'), ('SHIPPING', 'Order is on the way'), ('DONE', 'Order Completed'), ('CANCELED', 'Order Canceled')], default='PLACED', max_length=20),
        ),
    ]
