# Generated by Django 3.0.7 on 2020-07-21 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_auto_20200721_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, default='CASH ON', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(blank=True, default='PENDING', max_length=10, null=True),
        ),
    ]
